import type { Metadata } from "next";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  ArrowRight,
  Brain,
  MessageSquare,
  Zap,
  CheckCircle2,
  Sparkles,
  BarChart3,
  Users,
  Rocket,
  Building2,
} from "lucide-react";
import { DecorativeOrbs } from "@/components/decorative-orbs";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://turicks.com";

export const metadata: Metadata = {
  title: "AI-Ingested Websites That Generate Leads | BizSite AI by Turicks",
  description:
    "Get a website powered by AI — smart copy generated by agents, 24/7 AI chatbot, and autonomous lead outreach. Built for businesses that want results, not just a web presence.",
  keywords: [
    "AI-ingested websites",
    "AI website builder",
    "BizSite AI",
    "autonomous lead generation",
    "AI chatbot website",
    "AI-powered website",
    "website with AI chatbot India",
    "AI website creation",
    "automated lead generation website",
  ],
  openGraph: {
    title: "AI-Ingested Websites That Generate Leads | BizSite AI by Turicks",
    description:
      "Your website, powered by AI — smart copy, 24/7 AI chatbot, and autonomous lead outreach. Built for businesses that want results.",
    type: "website",
    url: `${SITE_URL}/ai-ingested-websites`,
    siteName: "Turicks",
    images: [{ url: `${SITE_URL}/og-image.svg`, width: 1200, height: 630 }],
  },
  twitter: {
    card: "summary_large_image",
    title: "AI-Ingested Websites | BizSite AI by Turicks",
    description:
      "AI writes your copy, chats with your leads, and finds prospects automatically. Get a website that actually generates business.",
    images: [`${SITE_URL}/og-image.svg`],
  },
  alternates: { canonical: "/ai-ingested-websites" },
};

const features = [
  {
    icon: Brain,
    title: "AI Researches & Writes Your Copy",
    description:
      "Our agents study your industry, analyze your competitors, and generate high-converting content that sounds like you — before you've written a single word. No briefs, no back-and-forth, no generic filler.",
    bullets: [
      "Competitor analysis by AI agents",
      "Industry-specific positioning",
      "Conversion-optimized headlines and CTAs",
      "Brand voice matching",
      "Auto-updated as your business evolves",
    ],
  },
  {
    icon: MessageSquare,
    title: "24/7 AI Sales Assistant, Built In",
    description:
      "Every BizSite AI site ships with a pre-trained chatbot that knows your offerings inside out. It qualifies leads, answers objections, schedules calls, and books meetings — at 2am if needed. No human required.",
    bullets: [
      "Pre-trained on your products & services",
      "Lead qualification and scoring",
      "Objection handling built in",
      "Meeting booking integration",
      "Handoff to your team when ready",
    ],
  },
  {
    icon: Zap,
    title: "Autonomous Prospect Outreach",
    description:
      "The BizSite AI engine identifies your ideal prospects based on your ICP, then sends them personalized website previews and introductions automatically. Your sales pipeline fills while you sleep.",
    bullets: [
      "ICP-based prospect identification",
      "Personalized outreach messages",
      "Website preview delivery",
      "Follow-up sequences",
      "Inbox-friendly deliverability",
    ],
  },
  {
    icon: BarChart3,
    title: "Analytics & Lead Intelligence",
    description:
      "See exactly who visited, what they looked at, which chatbot conversations converted, and which outreach sequences worked. Every lead interaction tracked and surfaced for your team.",
    bullets: [
      "Visitor tracking and heat maps",
      "Lead conversation transcripts",
      "Outreach performance dashboard",
      "Conversion funnel analytics",
      "CRM integration for lead handoff",
    ],
  },
];

const included = [
  "AI-generated, conversion-optimized copy for every page",
  "Custom design matched to your brand identity",
  "24/7 AI chatbot pre-trained on your products & services",
  "Autonomous lead outreach engine with personalization",
  "Analytics + lead tracking dashboard",
  "Mobile-responsive, fast-loading site",
  "SEO-optimized structure with schema markup",
  "2-week delivery from kickoff to live",
];

const audiences = [
  {
    icon: Rocket,
    title: "Startups",
    description:
      "You need a lead-gen machine from day one, not a brochure. BizSite AI gives you a presence that actively hunts for your first customers while you build.",
  },
  {
    icon: Building2,
    title: "Service Businesses",
    description:
      "Consultants, agencies, and service providers who want their website to close deals — not just look pretty. Every visitor gets a personalized, AI-powered experience.",
  },
  {
    icon: Users,
    title: "Agencies",
    description:
      "Offer AI-powered websites to your clients as a premium service. White-label BizSite AI and deliver a product your clients can't get anywhere else.",
  },
];

const faqs = [
  {
    q: "What is an AI-ingested website?",
    a: "An AI-ingested website is a site where AI agents have researched your business, written your copy, and built a 24/7 sales system around your offerings. It's not a template — it's a website that understands your business and works to grow it automatically.",
  },
  {
    q: "How is this different from using AI to write website copy?",
    a: "Using ChatGPT to write copy is just step one. An AI-ingested website includes an autonomous AI chatbot trained on your specific products, an outreach engine that finds and contacts prospects, and analytics that show you which leads are worth pursuing. It's a complete system, not just content.",
  },
  {
    q: "How long does it take to launch?",
    a: "2 weeks from kickoff to live site. We handle design, copy generation, chatbot training, and outreach setup in parallel. You review and approve before launch.",
  },
  {
    q: "Can the AI chatbot be trained on my specific products and pricing?",
    a: "Yes. We train the chatbot on your product descriptions, pricing, FAQs, case studies, and any other materials you provide. It knows your business as well as your best sales rep.",
  },
  {
    q: "Do I need to write any of the content myself?",
    a: "Minimal input is needed. We need a short brief about your business, your ideal customer, and your key offerings. Our agents handle the rest — research, copywriting, and optimization.",
  },
  {
    q: "What happens after launch?",
    a: "The AI continues to learn from visitor behavior and chatbot conversations. We provide a dashboard with lead activity, and your team gets notified when a qualified lead is ready for a conversation. We also offer monthly optimization calls.",
  },
];

export default function AiIngestedWebsitesPage() {
  const breadcrumbSchema = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: `${SITE_URL}/` },
      {
        "@type": "ListItem",
        position: 2,
        name: "AI-Ingested Websites",
        item: `${SITE_URL}/ai-ingested-websites`,
      },
    ],
  };

  const faqSchema = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.q,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.a,
      },
    })),
  };

  return (
    <div className="flex flex-col">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      {/* Hero */}
      <section className="relative overflow-hidden py-20 md:py-28">
        <DecorativeOrbs className="opacity-50" />
        <div className="container mx-auto px-4 relative">
          <div className="mx-auto max-w-4xl text-center">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border bg-primary/5 px-4 py-2 text-sm font-medium text-primary">
              <Sparkles className="h-4 w-4" />
              <span>BizSite AI · AI-Ingested Websites</span>
            </div>
            <h1 className="mb-6 text-4xl font-bold tracking-tight leading-tight sm:text-5xl md:text-6xl text-balance">
              Your Website, Powered by AI —{" "}
              <span className="text-primary">Generates Leads While You Sleep</span>
            </h1>
            <p className="mb-8 text-lg text-muted-foreground md:text-xl max-w-3xl mx-auto">
              BizSite AI doesn&apos;t build websites. It builds autonomous
              digital sales machines — pre-trained on your business, designed to
              convert, and programmed to grow your pipeline without you lifting
              a finger.
            </p>
            <div className="mb-10 flex flex-wrap justify-center gap-4 text-sm font-medium">
              <span className="flex items-center gap-2 rounded-full border bg-muted px-4 py-2">
                <Zap className="h-4 w-4 text-primary" /> Live in 2 weeks
              </span>
              <span className="flex items-center gap-2 rounded-full border bg-muted px-4 py-2">
                <MessageSquare className="h-4 w-4 text-primary" /> 24/7 AI chatbot
              </span>
              <span className="flex items-center gap-2 rounded-full border bg-muted px-4 py-2">
                <Brain className="h-4 w-4 text-primary" /> AI-written copy
              </span>
              <span className="flex items-center gap-2 rounded-full border bg-muted px-4 py-2">
                <BarChart3 className="h-4 w-4 text-primary" /> Lead tracking
              </span>
            </div>
            <div className="flex flex-col justify-center gap-3 sm:flex-row">
              <Button asChild size="lg">
                <Link href="/contact">
                  Get Your AI Website Preview — Free
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Link>
              </Button>
              <Button asChild variant="outline" size="lg">
                <Link href="/contact">Talk to the Team</Link>
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="relative overflow-hidden py-20 bg-muted/30">
        <div className="container mx-auto px-4">
          <div className="mb-12 text-center">
            <Badge variant="secondary" className="mb-4">What Makes BizSite AI Different</Badge>
            <h2 className="mb-4 text-3xl font-bold md:text-4xl">
              A Website That Sells For You, Around the Clock
            </h2>
            <p className="mx-auto max-w-2xl text-muted-foreground">
              Four systems working together — all built, trained, and deployed
              for your specific business.
            </p>
          </div>
          <div className="grid gap-6 md:grid-cols-2">
            {features.map((feature) => {
              const Icon = feature.icon;
              return (
                <Card key={feature.title} className="group bg-background/60 backdrop-blur">
                  <CardHeader>
                    <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10 transition-transform duration-300 group-hover:scale-110">
                      <Icon className="h-6 w-6 text-primary" />
                    </div>
                    <CardTitle className="text-xl">{feature.title}</CardTitle>
                    <CardDescription className="text-base">{feature.description}</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-2">
                      {feature.bullets.map((b) => (
                        <li key={b} className="flex items-start gap-2 text-sm text-muted-foreground">
                          <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
                          <span>{b}</span>
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* What's Included */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="mx-auto max-w-3xl">
            <div className="rounded-3xl border bg-gradient-to-br from-primary/5 to-accent/5 p-8 md:p-10">
              <Badge variant="secondary" className="mb-4">What&apos;s Included</Badge>
              <h2 className="mb-8 text-3xl font-bold md:text-4xl">
                Everything You Need, Nothing You Don&apos;t
              </h2>
              <ul className="space-y-4">
                {included.map((item) => (
                  <li key={item} className="flex items-start gap-3">
                    <CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-primary" />
                    <span className="text-foreground/90">{item}</span>
                  </li>
                ))}
              </ul>
              <div className="mt-8">
                <Button asChild size="lg" className="w-full sm:w-auto">
                  <Link href="/contact">
                    Get Your AI Website Preview
                    <ArrowRight className="ml-2 h-4 w-4" />
                  </Link>
                </Button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Who It&apos;s For */}
      <section className="relative overflow-hidden py-20 bg-muted/30">
        <DecorativeOrbs className="opacity-30" />
        <div className="container mx-auto px-4 relative">
          <div className="mb-12 text-center">
            <Badge variant="secondary" className="mb-4">Who It&apos;s For</Badge>
            <h2 className="mb-4 text-3xl font-bold md:text-4xl">
              Built for Businesses That Want Results
            </h2>
            <p className="mx-auto max-w-2xl text-muted-foreground">
              Not for businesses happy with a brochure site. For businesses that
              want their website to actively work for them.
            </p>
          </div>
          <div className="grid gap-6 md:grid-cols-3">
            {audiences.map((audience) => {
              const Icon = audience.icon;
              return (
                <Card key={audience.title} className="group bg-background/60 backdrop-blur text-center">
                  <CardHeader>
                    <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10 transition-transform duration-300 group-hover:scale-110">
                      <Icon className="h-7 w-7 text-primary" />
                    </div>
                    <CardTitle>{audience.title}</CardTitle>
                    <CardDescription>{audience.description}</CardDescription>
                  </CardHeader>
                </Card>
              );
            })}
          </div>
        </div>
      </section>

      {/* FAQs */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="mb-12 text-center">
            <Badge variant="secondary" className="mb-4">FAQ</Badge>
            <h2 className="mb-4 text-3xl font-bold md:text-4xl">
              Questions About AI-Ingested Websites
            </h2>
          </div>
          <div className="mx-auto max-w-3xl space-y-6">
            {faqs.map((faq) => (
              <div
                key={faq.q}
                className="rounded-2xl border bg-background/60 backdrop-blur p-6"
              >
                <h3 className="mb-3 font-semibold text-foreground">{faq.q}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">{faq.a}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t bg-primary/5 py-20">
        <div className="container mx-auto px-4 text-center">
          <h2 className="mb-4 text-3xl font-bold md:text-4xl">
            Stop Paying for a Website That Does Nothing
          </h2>
          <p className="mb-8 mx-auto max-w-2xl text-muted-foreground">
            Get a free AI-generated preview of what your BizSite AI website
            could look like. No commitment, no payment — just a preview of what
            your business could have in two weeks.
          </p>
          <div className="flex flex-col items-center justify-center gap-4 sm:flex-row">
            <Button asChild size="lg">
              <Link href="/contact">
                Get Your Free AI Preview
                <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
            <Button asChild size="lg" variant="outline">
              <Link href="/services">See All Services</Link>
            </Button>
          </div>
        </div>
      </section>
    </div>
  );
}
